activities/models.py
=> Vrppayment to date fix

dg/templates/social_website/vrppayment.html, vrppayment/views.py
update in vrp tool on Abhinav's request to change 60% to 70%
=> Vrp payment tool update 10 sept

loop/admin.py, loop/management/commands/loop_data_email.py, loop/models.py
=> Master loop lokesh

loop/migrations/0004_auto__del_unique_combinedtransaction_date_farmer_crop_mandi_price__add.py, loop/models.py
=> Master loop abhishek lodha

loop/api.py
timestamp added to handle duplicate in combined transaction
=> added timestamp while add or editing a combined transaction

training/api.py, training/migrations/0002_auto.py, training/models.py
New field added on trainingUser model and changed get_user_mediators for send data to training app based district of trainer.
=> Master training user assigned districts

loop/migrations/0007_auto__del_unique_combinedtransaction_date_farmer_crop_mandi_price_gadd.py, loop/models.py
Unique together changed for CT- uptil step 18
=> changed unique together constraints for CT

loop/management/commands/fill_timestamp.py, loop/migrations/0008_auto__add_field_daytransportation_is_visible__add_field_daytransportat.py, loop/models.py
DT modified with timestamp and is_visible, CT modifies with addition of is_visible and payment date - uptil step 26
=> added timestamp for DT, is visible fot CT and DT and payment date for CT

loop/migrations/0009_auto__add_unique_daytransportation_date_user_created_timestamp.py, loop/models.py
Unique together added in DT and corresponding migrations
=> Added timestamp and user created in Unique fields for DT

loop/api.py
=> reduced data to be sent from server for POST request

loop/api.py
ApiKey Auth added in state, district, block
=> Added block,district and state authentication

loop/api.py
api modified to support block, district, state get and post request
=> api modified to support block district and state

scripts/adding_MRP_standalone_script .py
code reviewed and checked-  ready to merge on prod
=> data migration script with folder locations as on server

scripts/adding_MRP_standalone_script .py
code reviewed and checked-  ready to merge on prod
=> script modified for prod

scripts/adding_MRP_standalone_script .py
code reviewed and checked-  ready to merge on prod
=> modified to work as standalone

MRP Database - Master.csv, mrppayment/management/commands/adding_MRP_standalone_script.py
standalone script made as management command
=> standalone script moved as command in management

dg/media/app_dashboards/js/training_dashboard.js
Date picker default range is set from January 2015 to current date
=> Master training dashboard

mrppayment/views.py
Bug Fixed :  http response rendering - deprecated mimetype changed to content-type
=> change mimetype to contenttype

loop/admin.py
english translation field added in admin list
=> Loop english language temp

loop/views.py
View modified to show english names on dashboard
=> Changed views to display english names only

loop/views.py
English Language Bug fix loop dashboard
=> Bug fixed dashboard english language

dg/media/app_dashboards/js/loop_dashboard.js, loop/views.py
=> Loop dashboard new template

dg/media/raw_data_analytics/raw_data_analytics.js, dg/templates/raw_data_analytics/output.html, raw_data_analytics/utils/configuration.py, raw_data_analytics/utils/data_library.py, raw_data_analytics/utils/initialize_data.py, raw_data_analytics/views.py
Group and video checkbox selected together resolved
=> case handling

scripts/download_from_s3.py, scripts/unrar_zip_rar_script.py
=> Dbscheduler

scripts/db_import.py, scripts/download_from_s3.py
=> script to import DB

activities/management/commands/adoption_mediator_assignment.py
=> Master loop migration bugfix

dg/templates/social_website/contact.html
=> San Francisco address added

ivr/migrations/0002_auto_20161202_1123.py, ivr/models.py, loop/migrations/0005_auto_20161202_1104.py, loop/models.py, loop/views.py
Migration added to add TESTING profile for loop user and to disable migration for ivr AUDIO model.
=> Alter loop tables

loop/views.py
=> transportation amount merging bug fix payment sheet

activities/management/commands/jslps_data_integration.py, activities/management/commands/jslps_screening_pma.py, activities/management/commands/jslps_videos_nn.py
1. Fixed duplication of entries.
=> Jslps data integration

loop/utils/loop_etl/get_aggregator_share.py, loop/views.py
added handling for daily payment model for aggregators
=> Aggregator payment method

dg/media/app_dashboards/js/loop_dashboard.js, dg/templates/app_dashboards/loop_dashboard.html, loop/views.py
Added 150 rupee for mobile recharge in payment sheet
=> Dashboard payment sheet changes

dg/media/app_dashboards/js/loop_dashboard.js, loop/payment_template.py
Comments added in payment sheet downloaded
=> comments added in loop payment excel sheet

activities/management/commands/bangladesh_villages.csv, activities/management/commands/upload_villages.py
Uplaod Village Script -  To add village to corresponding block, district and state; Assumption State and Country is added already.
=> Master upload village

loop/management/commands/loop_etl.py
Removed multiple insert commands and added a single list containing all data for inserting in myisam table
=> Loop etl optimisation

dg/media/app_dashboards/css/loopdashboard.css, dg/media/app_dashboards/js/loop_dashboard.js, dg/templates/app_dashboards/loop_dashboard.html, loop/admin.py, loop/management/commands/loop_etl.py, loop/management/commands/recreate_schema.sql, loop/utils/loop_etl/group_myisam_data.py, loop/views.py
Country filter added on loop dashboard.
Need to run loop etl after merging.
=> Loop dashboard country fix

dg/media/raw_data_analytics/raw_data_analytics.js, raw_data_analytics/views.py
bug fix and changes in video filter on state instead of district
=> raw_data_fix_and_filter_changed

loop/admin.py
Parameters added in different admin classes for smooth flow.
=> Changes in Loop admin Page

loop/admin.py
=> Loop admin

loop_ivr/views.py
1. 1/2 second gap before making return call for avoid call waiting at user side.
=> Market info line.

loop_ivr/helper_function.py, loop_ivr/management/commands/sms_push_service.py, loop_ivr/models.py, loop_ivr/utils/config.py
1. SMS format changed in both pull and push service.
=> Sms line mandi change

loop_ivr/admin.py, loop_ivr/management/commands/push_sms_email.py, loop_ivr/models.py
1. Send statistics of Market information line.
2. Search field added in price info incoming admin.
3. unicode changed for Subscription model.
=> Push sms email

loop_ivr/helper_function.py, loop_ivr/management/commands/push_sms_email.py, loop_ivr/utils/config.py
1. Message changed when no rates available for query.
2. Static crop codes added with above messages.
=> Mi template

loop/admin.py, loop/models.py
loopuser phone added for dropdown
=> Django admin changes

dg/templates/social_website/responsive/base_auth.html
Favicon fixes on admin pages (base_auth).
=> favicon fix on admin login page

loop_ivr/views.py
Limit 10 call per number per day
=> MI call restrict to 10

loop/views.py
Reverts digitalgreenorg/dg#847
=> Revert "Loop dashboard payment bug fix"

loop/api.py
=> authorization changed for adminuser in blockauth and daytransauth

loop_ivr/utils/config.py, loop_ivr/views.py
sending different http status on wrong or incorrect queries
=> Mi line update

loop_ivr/outliers/removal.py
Changed sort order of dataset after outliers are removed
=> changed dataframe sort order

loop/utils/send_log/send_sms.py
=> Sms bug fix

dg/media/app_dashboards/js/loop_dashboard_payment.js, loop/utils/loop_etl/get_aggregator_share.py, loop/views.py
This pull request fixes the following bugs:
1. Farmer correct phone date model being applied to all geographies; fixed to be applied to only Bihar
2. Subsequent changes in utils for myisam creation
3. Mobile recharge entry being ignored in total for column in downloaded payment sheet
=> Payment bug fixes

loop/dashboard_views.py
Filters based on loop user role added for farmers on home page
=> applying loop user filter on farmers for home page

loop/management/commands/bangladesh_kelly_stat.py
Updated email command for bangladesh farmers who have used loop atleast once in 2 years. Email updated according to requirement.
=> Updated bangladesh farmer stats for farmers who used loop atleast once

.vscode/settings.json, loop_ivr/admin.py, loop_ivr/helper_function.py, loop_ivr/management/commands/textlocal_sms_status.py, loop_ivr/migrations/0006_auto_20180320_0508.py, loop_ivr/migrations/0007_auto_20180320_1031.py, loop_ivr/models.py
Saving Textlocal sms id in another table
=> Loop mi model changes 2

loop_ivr/management/commands/textlocal_sms_status.py
=> filter changed to status

loop/views.py
Helpline fix for the case -  busy experts
=> Loop helpline fix

loop/api.py, loop/management/commands/referral.py, loop/models.py, loop/utils/send_log/registration.py
=> Loop ideo ivr automate

coco/views.py, dg/qacoco_admin.py, qacoco/admin.py
Bluefrog Video API error handling
=> Upload fix

dashboard/admin.py
Remove already mapped videos from the interface.
=> Bluefrog video mapping interface changes

activities/management/commands/ap_data_integration.py
=> email deleted

dashboard/admin.py
=> Bluefrog video mapping interfaces changes, added state filter

output/database/SQL/shared_sql.py
Geographies only with 'active = True' are shown in analytics
=> Ap geography duplicates removed

coco/views.py
Added a new column in the template file.
=> fathers name added in bulk

output/database/SQL/shared_sql.py, output/views/adoption_analytics.py, output/views/overview_analytics.py
=> analytics update

dg/media/Output/JS/overview_module.js, dg/media/Output/JS/video_module.js, dg/templates/output/adoption_module.html, dg/templates/output/overview_module.html, dg/templates/output/screening_module.html, dg/templates/output/video_module.html, output/database/SQL/shared_sql.py, output/views/adoption_analytics.py, output/views/common.py, output/views/video_analytics.py
=> Analytics3

output/management/commands/etl.py
=> etl bot created

output/database/SQL/adoption_analytics_sql.py, output/database/SQL/overview_analytics_sql.py, output/database/SQL/screening_analytics_sql.py, output/database/SQL/shared_sql.py, output/database/SQL/targets_sql.py, output/database/SQL/video_analytics_sql.py, output/database/utility.py, output/views/adoption_analytics.py, output/views/screening_analytics.py
- SQL queries for CoCo Analytics Dashboard changed
- app name 'output' files have been modified in this fix
- etl.py needs not to run now
- Processing of the numeric KPIs happen on-the-fly
- myisam tables usage by numeric KPIs code has been removed
- Graphs' SQL queries yet to be fixed
- Graphs' are using myisam tables
=> Analytics dashboard fix

coco/api.py, coco/data_log.py, coco/urls.py, coco/views.py, dashboard/admin.py, dashboard/forms.py, dg/coco_admin.py, dg/media/coco/app/scripts/user_initialize.js, dg/media/coco/dist/scripts/main.js, dg/media/coco/dist/scripts/qa_main.js, dg/media/configs.js, dg/media/dashboard.html, dg/media/js/filter_village.js, dg/media/qa_config.js, dg/media/qa_dashboard.html, dg/media/serviceworker.js, people/migrations/0019_auto_20231004_0806.py, people/migrations/0020_auto_20231005_0818.py, people/models.py, qacoco/admin.py, qacoco/api.py, qacoco/forms.py, qacoco/migrations/0006_auto_20230926_0832.py, qacoco/models.py
YouTube ID validation using RegExp
=> Eth-customizations
